ALTER TABLE scans ADD COLUMN IF NOT EXISTS ip_address TEXT;
ALTER TABLE scans ADD COLUMN IF NOT EXISTS device_vendor TEXT;
ALTER TABLE scans ADD COLUMN IF NOT EXISTS os_name TEXT;
ALTER TABLE scans ADD COLUMN IF NOT EXISTS browser_name TEXT;
ALTER TABLE scans ADD COLUMN IF NOT EXISTS browser_lang TEXT;
ALTER TABLE scans ADD COLUMN IF NOT EXISTS country TEXT;
ALTER TABLE scans ADD COLUMN IF NOT EXISTS city TEXT;
